"""Adiciona coluna foto à tabela Tarefa

Revision ID: 58bbef568674
Revises: 
Create Date: 2025-02-23 00:25:30.320312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bbef568674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_despesa')
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_column('foto')

    op.create_table('log_despesa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('despesa_id', sa.INTEGER(), nullable=False),
    sa.Column('valor_antigo', sa.FLOAT(), nullable=False),
    sa.Column('valor_novo', sa.FLOAT(), nullable=False),
    sa.Column('data_alteracao', sa.DATETIME(), nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
