"""Adicionando campo num_moradores

Revision ID: ed113df8739d
Revises: 58bbef568674
Create Date: 2025-02-23 00:37:19.055525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed113df8739d'
down_revision = '58bbef568674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_moradores', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casa', schema=None) as batch_op:
        batch_op.drop_column('num_moradores')

    # ### end Alembic commands ###
